// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtabjndnietpewvknjrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0YWJqbmRuaWV0cGV3dmtuanJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MTY4MjIsImV4cCI6MjA1NDA5MjgyMn0.NrVqEaLRyCt4ut8-9potmOH_3JsSbMr8aq8XyKv-Q7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);